# Generated by Django 2.2.6 on 2020-04-20 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_musician_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='albums',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
        ),
    ]
