# Generated by Django 2.2.6 on 2020-04-21 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_musician_albums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='albums',
        ),
    ]
